CREATE TABLE #BST (
N int,
P int
)

INSERT INTO #BST
SELECT 1,2 UNION ALL
SELECT 3,2 UNION ALL
SELECT 6,8 UNION ALL
SELECT 9,8 UNION ALL
SELECT 2,5 UNION ALL
SELECT 8,5 UNION ALL
SELECT 5,NULL

select distinct t.N,
CASE WHEN t.P IS NULL THEN 'Root'
	WHEN tp.N IS NULL THEN 'Leaf'
	ELSE 'Inner' END AS Type
from #BST as t
left join #BST as tp
ON t.N=tp.P